 LexEntry
    LexEntryRefLink
        LexEntryRefLink_OwningEntry
            Link
        LexEntryRef_VariantEntryTypes
            Link
    LexEntry_Etymology
        LexEntry_Etymology
            LexEtymology
                LexEtymology_Form
                    Astr
                LexEtymology_Gloss 
                    Astr
                LexEtymology_Source  
                    Astr
    LexEntry_HeadWord		
        Astr
    LexEntry_LiteralMeaning
        Astr
    LexEntry_Pronunciations
        LexPronunciation
            LexPronunciation_Form
                Astr 
    LexEntry_Senses
          LexEntry_Senses
              LexSense
                  LexSense_Definition
                      Astr
                  LexSense_Examples
                      LexExampleSentence
                          LexExampleSentence_Example
                              Astr
                          LexExampleSentence_Translations
                              LexExampleSentence_Translations
                                  CmTranslation
                                      CmTranslation_Translation
                                            Astr					      
                  LexSense_Gloss
                      LexSense_Gloss
                          Astr
                    LexSense_LexSenseReferences
                          LexSense_LexSenseReferences
                                LexReferenceLink
                                    LexReferenceLink_Type
                                        Link
                                    LexReference_Targets
                                        LexReference_Targets
                                            Link
                    LexSense_ScientificName		
                        Str
                    LexSense_UsageTypes
                        Link
                    LexSense_VariantFormEntryBackRefs
                        LexEntryRefLink
                            LexEntryRefLink
                                LexEntryRefLink_OwningEntry
                                    Link
                                LexEntryRef_VariantEntryTypes
                                    Link
                    LexSense_lexical_function_glosses
                          Str
                    MoMorphSynAnalysisLink_MLPartOfSpeech
                          Astr	
    LexEntry_plural_form
        Str
    LexReferenceLink
    MoStemMsa
        MoStemMsa_MLPartOfSpeech
            Astr